// Author - Emeka Umeozo

#ifndef DISTANCE_VECTOR_ROUTING_SIMUL_KAFKAPROP_H
#define DISTANCE_VECTOR_ROUTING_SIMUL_KAFKAPROP_H
#define kafkaURL "localhost:9092"
#endif //DISTANCE_VECTOR_ROUTING_SIMUL_KAFKAPROP_H
